#!/usr/bin/env bash

unicode=" "

_black=$(tput setaf 0)
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
magenta=$(tput setaf 5)
cyan=$(tput setaf 6)
_white=$(tput setaf 7)
_bright=$(tput bold)
normal=$(tput sgr0)
# _underline=$(tput smul) # No se usa en el script, puedes quitarlo

# up=$(uptime -p | sed 's/up //; s/ days,/d/; s/ day,/d/; s/ hours,/h/; s/ hour,/h/; s/ minutes/m/; s/ minute/m/; s/\s//g')
up=$(uptime | awk -F'( |,|:)+' '{
        d=h=m=0;
        if ($7=="min" || $7=="mins")
            m=$6;
        else {
            if ($7~/^day/) { d=$6; h=$8; m=$9}
            else {h=$6;m=$7}
        }
    }
    { printf "%dh%dm", h, m }
')

pkgs=$(pacman -Q | wc -l)
mem=$(free -h | awk 'NR==2 {print $3 "/" $2}')

gpu_info=$(lspci | grep -i 'vga\|3d\|2d')
if [[ "$gpu_info" == *\[*\]* ]]; then
    gpu=$(echo "${gpu_info}" | awk -F '[][]' '{print $2; exit}')
else
    gpu=$(echo "${gpu_info}" | awk -F': ' '{print $NF; exit}' | sed 's/(rev [^)]*)//' | awk '{$1=$1;print}')
fi
# Si prefieres el original exacto y sabes que siempre tendrás corchetes:
# gpu=$(lspci | grep -i vga | awk -F '[][]' '{print $2}')

fetch() {
    # echo "${cyan}${_bright}     _  ___      ____  ____    ${normal}"
    # echo "${cyan}${_bright}    / |/ (_)_ __/ __ \/ __/    ${normal}"
    # echo "${cyan}${_bright}   /    / /\ \ / /_/ /\ \      ${normal}"
    # echo "${cyan}${_bright}  /_/|_/_//_\_\\____/___/  ${normal}"

 echo "${cyan}${_bright}                  __    ${normal}"
 echo "${cyan}${_bright}    ___ _________/ /    ${normal}"
 echo "${cyan}${_bright}   / _ \`/ __/ __/ _ \  ${normal}"
 echo "${cyan}${_bright}   \_,_/_/  \__/_//_/   ${normal}"

    echo ""
    echo "  ╭─────────────╮ "
    echo "  │  ${red} ${normal} user    │ ${red}$(whoami)${normal}"
    echo "  │  ${yellow} ${normal} distro  │ ${yellow}$(grep PRETTY_NAME /etc/os-release | sed 's/PRETTY_NAME="\(.*\)"/\1/')${normal} "
    echo "  │  ${green} ${normal} kernel  │ ${green}$(uname -r)${normal} "
    echo "  │  ${cyan}󱂬 ${normal} de/wm   │ ${cyan}${XDG_CURRENT_DESKTOP}${normal} "
    echo "  │  ${blue} ${normal} uptime  │ ${blue}${up}${normal} "
    echo "  │  ${magenta} ${normal} shell   │ ${magenta}$(basename "${SHELL}")${normal} "
    echo "  │  ${red}󰏖 ${normal} pkgs    │ ${red}${pkgs}${normal} "
    echo "  │  ${yellow} ${normal} gpu     │ ${yellow}${gpu}${normal} "
    echo "  │  ${green}󰍛 ${normal} mem     │ ${green}${mem}${normal} "
    echo "  ├─────────────┤ "
    echo "  │  ${_white}  ${normal}colors  │${_white}$unicode${normal}${red}$unicode${normal}${yellow}$unicode${normal}${green}$unicode${normal}${cyan}$unicode${normal}${blue}$unicode${normal}${magenta}$unicode${normal}${_black}$unicode${normal}"
    echo "  ╰─────────────╯ "
}

fetch && exit 0
